### ISSUE TITLE
QuickSearch launch shortcut on OS X

### ISSUE THREAD

**Issue by pan-pawka** [appetizermonster/Unity3D-QuickSearch#1]
Hey,

QuickSearch on OS X won't work because this shortcut **CMD + , / CTRL + ,**  is reserved for Preferences panel.

![Unity3D Preferences](https://cloud.githubusercontent.com/assets/9073871/18660758/9ed3f12c-7f12-11e6-89fc-d939182733c4.png)

QuickFix for QuickSearch. Just open QuickSearchController.cs, and edit this line of code:

> [MenuItem("Window/Toggle QuickSearch %,")]

You can change **%,** to any other free key combination: 
- %(ctrl on Windows, cmd on OS X) 
- #(shift) 
- &(alt)

For example: 
- **CTRL + t / CMD + t** `[MenuItem("Window/Toggle QuickSearch %t")]`
- **SHIFT + ,** `[MenuItem("Window/Toggle QuickSearch %,")]`
- **ALT + q** `[MenuItem("Window/Toggle QuickSearch &q")]`

@appetizermonster you could add some platform dependency to this line for future uses or change shortcut ;)

```
#if UNITY_EDITOR_OSX
[MenuItem("Window/Toggle QuickSearch #`")]
#else
[MenuItem("Window/Toggle QuickSearch %,")]
#endif
```

**Comment by appetizermonster** [comment]
Thanks for the suggestion!, I have added your code just before!
